### PR TITLE
Correct package name

### PR DESCRIPTION
**Pull request by syohex**

### CODE REVIEW

**Comment by kuangdash** [comment]
Thanks~!

**Comment by kuangdash** [comment]
Do I need to pull-request (to melpa) again in order to make it pass?

**Comment by syohex** [comment]
No. Can you rerun test from travis-ci web interface? Or you can test again by `git commit --amend`(you need not to change commit log) and `git push -f your_remove_repository your_branch`.

**Comment by kuangdash** [comment]
I have got a good answer here: 
http://stackoverflow.com/questions/17606874/trigger-a-travis-ci-rebuild-without-pushing-a-commit

Thanks~!

**Pull request merged**
